export const productos = [
  {
    id: "BP1234",
    marca: "BOSCH",
    nombre: "Pastillas de Freno Delanteras Bosch",
    codigo: "BP1234",
    precio: 2450,
    categoria: "Frenos",
    imagen: "https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?q=80&w=600&auto=format&fit=crop",
    descripcion: "Pastillas de freno delanteras Bosch de alta performance. Diseñadas para brindar máxima seguridad y frenado eficiente.",
    stock: 12,
    especificaciones: [
      ["Posición", "Delanteras"],
      ["Sistema de freno", "Disco"],
      ["Ancho", "156,3 mm"],
      ["Alto", "58,7 mm"],
      ["Espesor", "17,5 mm"],
      ["Material", "Semi-metálico"],
    ],
    aplicaciones: [
      "Volkswagen Gol 2019 Highline 1.6 MSI",
      "Volkswagen Gol 2018 1.6 MSI",
      "Volkswagen Voyage 2019 1.6 MSI",
    ],
    garantia: "6 meses por defectos de fabricación.",
    opiniones: [
      { nombre: "Martín", estrellas: 5, texto: "Muy buena calidad y encajaron perfecto." },
      { nombre: "Lucía", estrellas: 5, texto: "Llegaron rápido y el producto es excelente." },
      { nombre: "Santiago", estrellas: 4, texto: "Buena relación calidad-precio." },
    ],
  },
  {
    id: "BRD1234",
    marca: "BREMBO",
    nombre: "Discos de Freno Delanteros",
    codigo: "BRD1234",
    precio: 4200,
    categoria: "Frenos",
    imagen: "https://images.unsplash.com/photo-1504215680853-026ed2a45def?q=80&w=600&auto=format&fit=crop",
    descripcion: "Discos de freno delanteros Brembo diseñados para ofrecer una respuesta de frenado estable y confiable.",
    stock: 8,
    especificaciones: [
      ["Posición", "Delanteros"],
      ["Tipo", "Disco ventilado"],
      ["Diámetro", "256 mm"],
      ["Material", "Acero"],
    ],
    aplicaciones: ["Volkswagen Gol 2018-2020", "Volkswagen Voyage 2018-2020"],
    garantia: "6 meses por defectos de fabricación.",
    opiniones: [
      { nombre: "Diego", estrellas: 5, texto: "Excelente terminación." },
      { nombre: "Pablo", estrellas: 4, texto: "Buen producto para uso diario." },
    ],
  },
  {
    id: "TRWS678",
    marca: "TRW",
    nombre: "Kit de Frenos Delanteros TRW",
    codigo: "TRWS678",
    precio: 6890,
    categoria: "Frenos",
    imagen: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?q=80&w=600&auto=format&fit=crop",
    descripcion: "Kit de frenos delanteros TRW para una renovación completa del sistema de frenado.",
    stock: 6,
    especificaciones: [
      ["Posición", "Delanteros"],
      ["Sistema", "Disco"],
      ["Marca", "TRW"],
      ["Contenido", "Kit completo"],
    ],
    aplicaciones: ["Volkswagen Gol", "Volkswagen Fox", "Volkswagen Voyage"],
    garantia: "6 meses por defectos de fabricación.",
    opiniones: [{ nombre: "Nicolás", estrellas: 5, texto: "Muy completo y fácil de instalar." }],
  },
  {
    id: "ATEDOT4",
    marca: "ATE",
    nombre: "Líquido de Freno DOT 4",
    codigo: "ATEDOT4",
    precio: 890,
    categoria: "Frenos",
    imagen: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=600&auto=format&fit=crop",
    descripcion: "Líquido de frenos DOT 4 para sistemas hidráulicos de frenado.",
    stock: 20,
    especificaciones: [
      ["Tipo", "DOT 4"],
      ["Presentación", "1 litro"],
      ["Uso", "Sistema hidráulico"],
    ],
    aplicaciones: ["Vehículos compatibles con DOT 4"],
    garantia: "Garantía de producto según fabricante.",
    opiniones: [{ nombre: "Andrés", estrellas: 5, texto: "Buen producto y buen precio." }],
  },
  {
    id: "MFA1234",
    marca: "MANN FILTER",
    nombre: "Filtro de Aire",
    codigo: "MFA1234",
    precio: 1290,
    categoria: "Filtros",
    imagen: "https://images.unsplash.com/photo-1615906655593-ad0386982a0f?q=80&w=600&auto=format&fit=crop",
    descripcion: "Filtro de aire MANN FILTER para mantener el flujo de aire limpio hacia el motor.",
    stock: 15,
    especificaciones: [
      ["Tipo", "Filtro de aire"],
      ["Marca", "MANN FILTER"],
      ["Material", "Fibra filtrante"],
    ],
    aplicaciones: ["Volkswagen Gol", "Volkswagen Voyage"],
    garantia: "6 meses por defectos de fabricación.",
    opiniones: [{ nombre: "Federico", estrellas: 5, texto: "Muy buena calidad." }],
  },
  {
    id: "MN7821",
    marca: "MONROE",
    nombre: "Amortiguador Delantero",
    codigo: "MN7821",
    precio: 5890,
    categoria: "Suspensión",
    imagen: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?q=80&w=600&auto=format&fit=crop",
    descripcion: "Amortiguador delantero Monroe diseñado para mejorar estabilidad y confort de marcha.",
    stock: 7,
    especificaciones: [
      ["Posición", "Delantera"],
      ["Tipo", "Gas"],
      ["Marca", "Monroe"],
    ],
    aplicaciones: ["Volkswagen Gol 2018-2020"],
    garantia: "6 meses por defectos de fabricación.",
    opiniones: [{ nombre: "Juan", estrellas: 4, texto: "Buen comportamiento en ruta." }],
  },
];

export const categorias = [
  { nombre: "Frenos", cantidad: 28 },
  { nombre: "Motor", cantidad: 43 },
  { nombre: "Suspensión", cantidad: 25 },
  { nombre: "Transmisión", cantidad: 18 },
  { nombre: "Electricidad", cantidad: 37 },
  { nombre: "Filtros", cantidad: 16 },
  { nombre: "Accesorios", cantidad: 22 },
];
